@Api_HostAddress = https://localhost:5050


### Get Products
GET {{Api_HostAddress}}/products
Accept: application/json

### Get Products With Pagination
GET {{Api_HostAddress}}/products?PageIndex=2&PageSize=2
Accept: application/json

### Create Product
POST {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Name": "New Product A",
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
  }
}

> {% client.global.set("new_product_id", response.body.id); %}

### Update Product
PUT {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Id": "{{new_product_id}}",
    "Name": "New Product A Update",
    "Category": ["c1", "c2", "c3"],
    "Description": "Description Product A Update",
    "ImageFile": "ImageFile Product A Update",
    "Price": 300
  }
}

### Get Products By Id
GET {{Api_HostAddress}}/products/{{new_product_id}}
Accept: application/json

> {% client.global.set("new_product_category", response.body.product.category[0]); %}

### Get Products By Category
GET {{Api_HostAddress}}/products/category/{{new_product_category}}
Accept: application/json

### Delete Product
DELETE {{Api_HostAddress}}/products/{{new_product_id}}
Accept: application/json

### Create Product With Error
POST {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
  }
}

### Update Product With Error
PUT {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Name": "New Product A Update",
    "Category": ["c1", "c2", "c3"],
    "Description": "Description Product A Update",
    "ImageFile": "ImageFile Product A Update",
    "Price": 300
  }
}

###
