@Api_HostAddress = https://localhost:5050
@User_Name = daniel

### Get Products
GET {{Api_HostAddress}}/products
Accept: application/json

### Get Products With Pagination
GET {{Api_HostAddress}}/products?PageIndex=2&PageSize=2
Accept: application/json

### Create Product
POST {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Name": "New Product A",
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
  }
}

> {% client.global.set("new_product_id", response.body.id); %}

### Update Product
PUT {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Id": "{{new_product_id}}",
    "Name": "New Product A Update",
    "Category": ["c1", "c2", "c3"],
    "Description": "Description Product A Update",
    "ImageFile": "ImageFile Product A Update",
    "Price": 300
  }
}

### Get Products By Id
GET {{Api_HostAddress}}/products/{{new_product_id}}
Accept: application/json

> {% client.global.set("new_product_category", response.body.product.category[0]); %}

### Get Products By Category
GET {{Api_HostAddress}}/products/category/{{new_product_category}}
Accept: application/json

### Delete Product
DELETE {{Api_HostAddress}}/products/{{new_product_id}}
Accept: application/json

### Create Product With Error
POST {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
  }
}

### Update Product With Error
PUT {{Api_HostAddress}}/products
Content-Type: application/json

{
  "Product": {
    "Name": "New Product A Update",
    "Category": ["c1", "c2", "c3"],
    "Description": "Description Product A Update",
    "ImageFile": "ImageFile Product A Update",
    "Price": 300
  }
}

### Create Basket
POST {{Api_HostAddress}}/basket
Content-Type: application/json

{
  "ShoppingCart": {
    "UserName": "{{User_Name}}",
    "Items": [
      {
        "ProductId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
        "Quantity": 2,
        "Color": "Red",
        "Price": 500,
        "ProductName": "IPhone X"
      },
      {
        "ProductId": "c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914",
        "Quantity": 1,
        "Color": "Blue",
        "Price": 500,
        "ProductName": "Samsung 10"
      }
    ]
  }
}

### Get Basket
GET {{Api_HostAddress}}/basket/{{User_Name}}
Accept: application/json

### Delete Basket
DELETE {{Api_HostAddress}}/basket/{{User_Name}}
Accept: application/json

### Add Item Into Basket New
POST {{Api_HostAddress}}/basket/{{User_Name}}/items
Content-Type: application/json

{
  "ShoppingCartItem": {
    "ProductId": "6ec1297b-ec0a-4aa1-be25-6726e3b51a27",
    "Quantity": 3,
    "Color": "Black",
    "Price": 460,
    "ProductName": "Xiaomi Mi"
  }
}

### Add Item Into Basket Existing
POST {{Api_HostAddress}}/basket/{{User_Name}}/items
Content-Type: application/json

{
  "ShoppingCartItem": {
    "ProductId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
    "Quantity": 2,
    "Color": "Red",
    "Price": 500,
    "ProductName": "IPhone X"
  }
}

### Remove Item Into Basket Existing
DELETE {{Api_HostAddress}}/basket/{{User_Name}}/items/5334c996-8457-4cf0-815c-ed2b77c4ff61
Accept: application/json

###
